INSERT INTO STUDENTS(AGE,ID,NAME)
VALUES
       (26,1,'Pesho'),
       (26,2,'Anna');

INSERT INTO COURSE(ENABLED,PRICE,ID,NAME)
VALUES
(0,200,1,'Spring'),
(1,300,2,'angular');

INSERT INTO ORDERS(COURSE_ID,ID,STUDENT_ID)
VALUES
(1,1,2),
(2,2,2),
(2,3,1);
